apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |-
    requirepass %%PASSWORD%%
    appendonly yes
    protected-mode yes
    bind 0.0.0.0
    port 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-start
data:
  config-start.sh: |
    #!/bin/bash
    mkdir -p /usr/local/etc/redis
    sed s/%%PASSWORD%%/$REDIS_PASSWORD/g /config/redis.conf > /usr/local/etc/redis/redis.conf
    redis-server /usr/local/etc/redis/redis.conf
