# redis.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: crypto
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    namespace: crypto
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
      namespace: crypto
  template:
    metadata:
      labels:
        app: redis
        namespace: crypto
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: redis
          image: public.ecr.aws/docker/library/redis:6.0.16
          imagePullPolicy: IfNotPresent
          command:
            - "/script/config-start.sh"
          ports:
            - containerPort: 6379
              name: http-redis
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
          - name: SERVICE_NAME
            value: redis
          - name: SERVICE_ENVIRONMENT
            value: prod
          - name: LOG_LEVEL
            value: WARN
          - name: MASTER
            value: "true"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rediscred
                key: password
          volumeMounts:
            - mountPath: /data
              name: redis-data
            - mountPath: /config
              name: redis-config
            - name: script
              mountPath: "/script"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config
        - name: script
          configMap:
            name: config-start
            defaultMode: 0500
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: crypto
spec:
  selector:
    app: redis
    namespace: crypto
  type: LoadBalancer
  sessionAffinity: None
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 172.16.0.202
  ports:
    - port: 6379
      protocol: TCP
      targetPort: http-redis